### PR TITLE
Add my name to the .env

### PR DESCRIPTION
**Pull request by johnsciutto**

### CODE REVIEW

**Review by jessdesr — APPROVED** [review]
Wicked, would you mind also removing the other names from the list?

**Comment by jessdesr** [comment]
Oh, and additional note: you'll want to add people to the Reviewers section, not the Assignees section 👍

**Comment by johnsciutto** [comment]
Awesome! Done deleting the other names.
Thanks for the correction about reviewers vs assignees!

**Review by jessdesr — APPROVED** [review]
Looks good, you also added a .env file to the root of the project though?  You can take that out and then this can be merged.

**Pull request merged**
